#!/usr/bin/env python
# -*- coding: utf8 -*-

import os
source = "https://raw.github.com/baijian/bootstrap.py/v1.1/bootstrap.py"
target = "%s/bootstrap.py" % os.path.dirname(os.path.abspath(__file__))
if not os.path.isfile(target):
    os.system("wget %s -O %s" % (source, target))


from bootstrap import bootstrap, ve
bootstrap(os.path.dirname(os.path.abspath(__file__)) + "/..")


ve("pip install Fabric==1.6.0")
ve("pip install fabtools==0.13.0")
ve("pip install Flask==0.10.1")
ve("pip install Flask-SQLAlchemy==0.16")
ve("pip install Flask-OAuth==0.12")
ve("pip install Flask-Login==0.2.11")
ve("pip install Flask-Cache==0.13.1")
ve("pip install requests==2.4.1")
ve("pip install uWSGI==2.0.8")
ve("pip install oursql==0.9.3.1")
ve("pip install Flask-Script==2.0.5")
